---
- hosts: master
  become: true
  tasks:
  - name: Initialize kubeadm
    become: true
    check_mode: true
    command: "kubeadm init"

  - name: Make .kube folder
    command: mkdir -p /home/ansible/.kube

  - name: Make copy config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/ansible/.kube/config
      force: yes
      remote_src: yes

  - name: Own the config file
    shell: "chown $(id -u):$(id -g) /home/ansible/.kube/config"

  - name: Add the kubeconfig file to bashrc
    lineinfile: dest=/root/.bashrc line='export KUBECONFIG=$HOME/.kube/config'

  - name: Source the bashrc file
    become: true
    shell: source /root/.bashrc
    args:
      executable: /bin/bash

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command.sh"